version: "2"
run:
  modules-download-mode: readonly
  build-tags:
    - evm
    - e2e
    - docker
linters:
  enable:
    - errorlint
    - gosec
    - misspell
    - revive
    - unconvert
  settings:
    gosec:
      excludes:
        - G115
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: duplicated-imports
          severity: warning
        - name: exported
          arguments:
            - disableStutteringCheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/rollkit)
        - prefix(github.com/rollkit/rollkit)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
